add: setup all schemas frontend
bakaqc/evora-17c pull request #51
Opened 2024-12-24 14:26 UTC by thanglp163

2024-12-24 14:43 UTC, bakaqc commented on frontend/src/schemas/booking.schema.ts
> +  user: User[];
type of user is User not User[ ]

2024-12-24 14:44 UTC, bakaqc commented on frontend/src/schemas/booking.schema.ts
> +  party?: Party[];
type of party is Party not Party[ ]

2024-12-24 14:51 UTC, theqi106 approved these changes

2024-12-24 15:01 UTC, bakaqc commented on frontend/src/schemas/notify.schema.ts
> +	user: User;
type of user is User[ ] not User

2024-12-24 15:02 UTC, bakaqc commented on frontend/src/schemas/party.schema.ts
> +	category: string;
false
should: enum: ['Sinh nhật', 'Đám cưới', 'Khai trương', 'Thôi nôi'],

2024-12-24 15:03 UTC, bakaqc commented on frontend/src/schemas/party.schema.ts
> +	options: 'tiệc cưới' | 'sinh nhật' | 'thôi nôi' | 'khai trương';
false
follow: 
type: {
					type: String,
					enum: ['Basic', 'Premium', 'VIP'],
					required: true,
},
price: { type: Number, required: true },

2024-12-24 15:05 UTC, bakaqc commented on frontend/src/schemas/payment.schema.ts
> +	voucher?: Voucher[];
type of voucher is Voucher not Voucher[ ]

2024-12-24 15:05 UTC, bakaqc commented on frontend/src/schemas/payment.schema.ts
> +	method: 'vn-pay' | 'momo' | 'zalo-pay';
method don't have vn-pay

2024-12-24 18:50 UTC, thanglp163 commented on frontend/src/schemas/notify.schema.ts
> +	user: User;
done

2024-12-25 00:28 UTC, bakaqc commented on frontend/src/schemas/booking.schema.ts
> +  party?: Party;
party is require not optional

2024-12-25 00:30 UTC, bakaqc commented on frontend/src/schemas/booking.schema.ts
> +  organizeDate?: Date;
require not optional

2024-12-25 00:31 UTC, bakaqc commented on frontend/src/schemas/booking.schema.ts
> +  payment: Payment;
optional not  require

2024-12-25 00:32 UTC, bakaqc commented on frontend/src/schemas/notify.schema.ts
> +	user: User;
haven't fix

2024-12-25 00:35 UTC, bakaqc commented on frontend/src/schemas/party.schema.ts
> +	description: string;
where is `option` attribute?

2024-12-25 00:36 UTC, bakaqc commented on frontend/src/schemas/party.schema.ts
> +	price: number;
follow database haven't `price`

2024-12-25 00:50 UTC, bakaqc commented on frontend/src/schemas/user.schema.ts
> +	verificationCode: string;
optional not require

2024-12-25 00:51 UTC, bakaqc commented on frontend/src/schemas/user.schema.ts
> +	verificationCodeExpires: Date;
optional not require

2024-12-25 00:51 UTC, bakaqc commented on frontend/src/schemas/user.schema.ts
> +	isVerified: boolean;
optional not require

2024-12-25 00:54 UTC, bakaqc requested changes
fix all comment before merge

2024-12-25 14:35 UTC, bakaqc commented on frontend/src/schemas/party.schema.ts
> +	options: string[];
type of option is false
follow:
options: Option[ ];

export interface Option {
	type: 'Basic' | 'Premium' | 'VIP';
	price: number;
}

2024-12-26 01:18 UTC, bakaqc approved these changes

2024-12-26 07:01 UTC, merged